# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: "수 빈"
tagline: "if(life){code();}"
description: 'life: Compiling… Please Wait'
url: "https://IDKwIhtd.github.io"
baseurl: ""

author:            
  name: "CHOI SUBIN"
  url: "http://zeroto.dothome.co.kr"

paginate: 1

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - "jekyll-sitemap"

sidebar_home_link: true
